### PR TITLE
changed CONTACT and CONTACT_URL

### PR DESCRIPTION
**Pull request by hasimpson-usgs**
Fixes usgs/geomag-website#51

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
Fixes usgs/geomag-website#51

**Comment by hasimpson-usgs** [comment]
Changes made.

**Comment by jmfee-usgs** [comment]
`$CONTACT` should be a full email address:

```
src/htdocs/about.php:    $CONTACT = 'geomag_research';
src/htdocs/conductivity/index.php:    $CONTACT = 'geomag_research';
src/htdocs/contact.php:    $CONTACT = 'geomag_research';
src/htdocs/learn/index.php:  $CONTACT = 'geomag_research';
src/htdocs/learn/introtogeomag.php:  $CONTACT = 'geomag_research';
src/htdocs/learn/pressreleases.php:  $CONTACT = 'geomag_research';
src/htdocs/learn/reading.php:  $CONTACT = 'geomag_research';
src/htdocs/partners.php:  $CONTACT = 'geomag_research';
src/htdocs/research/GIC.php:  $CONTACT = 'geomag_research';
src/htdocs/research/extreme-events.php:  $CONTACT = 'geomag_research';
src/htdocs/research/geomagnetism-earthquakes.php:  $CONTACT = 'geomag_research';
src/htdocs/research/hazards.php:  $CONTACT = 'geomag_research';
src/htdocs/research/index.php:  $CONTACT = 'geomag_research';
src/htdocs/research/magdataquality.php:  $CONTACT = 'geomag_research';
src/htdocs/research/spaceclimatology.php:  $CONTACT = 'geomag_research';
src/htdocs/research/spaceweather.php:  $CONTACT = 'geomag_research';
```

**Comment by hasimpson-usgs** [comment]
Ok,  one more time.

**Comment by jmfee-usgs** [comment]
`/contactus/` doesn't seem like the correct url.

**Comment by lisa-usgs** [comment]
It's contact.php in the root dir.

**Comment by hasimpson-usgs** [comment]
how about /contact.php

**Pull request merged**
